{
 "title": "Kafka Overview (Graphite)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "hostname", "label": "Hostname", "query": "servers.*" }
  ]
 },
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ActiveControllerCount",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.kafka.ActiveControllerCount)"
    }
   ]
  },
  {
   "title": "OfflinePartitionsCount",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.kafka.OfflinePartitionsCount)"
    }
   ]
  },
  {
   "title": "UnderReplicatedPartitions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.kafka.UnderReplicatedPartitions, *)"
    }
   ]
  },
  {
   "title": "UnderMinIsrPartitionCount",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.kafka.UnderMinIsrPartitionCount)"
    }
   ]
  },
  {
   "title": "Bytes In/Out - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(servers.$hostname.kafka.BrokerTopicMetrics.BytesInPerSec.*.OneMinuteRate, '__consumer_offsets'), 5, 4, 6)"
    },
    {
     "target": "aliasByNode(exclude(servers.$hostname.kafka.BrokerTopicMetrics.BytesOutPerSec.*.OneMinuteRate, '__consumer_offsets'), 5, 4, 6)"
    }
   ]
  },
  {
   "title": "Bytes In/Out - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(servers.$hostname.kafka.BrokerTopicMetrics.BytesInPerSec.*.OneMinuteRate, '__consumer_offsets'), 5, 4, 6)"
    },
    {
     "target": "aliasByNode(exclude(servers.$hostname.kafka.BrokerTopicMetrics.BytesOutPerSec.*.OneMinuteRate, '__consumer_offsets'), 5, 4, 6)"
    }
   ]
  },
  {
   "title": "Bytes In/Out - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(servers.$hostname.kafka.BrokerTopicMetrics.BytesInPerSec.*.OneMinuteRate, '__consumer_offsets'), 5, 4, 6)"
    },
    {
     "target": "aliasByNode(exclude(servers.$hostname.kafka.BrokerTopicMetrics.BytesOutPerSec.*.OneMinuteRate, '__consumer_offsets'), 5, 4, 6)"
    }
   ]
  },
  {
   "title": "RequestsPerSec - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$hostname.kafka.RequestMetrics.RequestsPerSec.*.MeanRate, 5, 6)"
    }
   ]
  },
  {
   "title": "RequestsPerSec - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$hostname.kafka.RequestMetrics.RequestsPerSec.*.MeanRate, 5, 6)"
    }
   ]
  },
  {
   "title": "RequestsPerSec - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$hostname.kafka.RequestMetrics.RequestsPerSec.*.MeanRate, 5, 6)"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "HeapMemoryUsage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(servers.$hostname.kafka.jvm.HeapMemoryUsage.*)"
    }
   ]
  },
  {
   "title": "HeapMemoryUsage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(servers.$hostname.kafka.jvm.HeapMemoryUsage.*)"
    }
   ]
  },
  {
   "title": "HeapMemoryUsage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(servers.$hostname.kafka.jvm.HeapMemoryUsage.*)"
    }
   ]
  },
  {
   "title": "NonHeapMemoryUsage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(servers.$hostname.kafka.jvm.NonHeapMemoryUsage.*)"
    }
   ]
  },
  {
   "title": "NonHeapMemoryUsage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(servers.$hostname.kafka.jvm.NonHeapMemoryUsage.*)"
    }
   ]
  },
  {
   "title": "NonHeapMemoryUsage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(servers.$hostname.kafka.jvm.NonHeapMemoryUsage.*)"
    }
   ]
  },
  {
   "title": "TheadCount - $hostname",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(servers.$hostname.kafka.jvm.ThreadCount)"
    }
   ]
  },
  {
   "title": "TheadCount - $hostname",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(servers.$hostname.kafka.jvm.ThreadCount)"
    }
   ]
  },
  {
   "title": "TheadCount - $hostname",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(servers.$hostname.kafka.jvm.ThreadCount)"
    }
   ]
  },
  {
   "title": "GarbageCollector - $hostname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2357",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:2355", "field": "select field", "id": "1", "type": "count" }
     ],
     "target": "aliasByNode(servers.$hostname.kafka.jvm.G1_Old_Generation.*, 4, 5)",
     "timeField": "@timestamp"
    },
    {
     "target": "aliasByNode(servers.$hostname.kafka.jvm.G1_Young_Generation.*, 4, 5)"
    }
   ]
  }
 ]
}