{
 "title": "System Kafka (Metricbeat)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "{\"find\":\"terms\",\"field\":\"beat.hostname\",\"query\":\"beat.hostname:kafka-*\"}"
   }
  ]
 },
 "panels": [
  { "title": "Load - $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "mo - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.load.5",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System load - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:324",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:322",
       "field": "system.load.1",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:load AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:353",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:351",
       "field": "system.load.5",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:load AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:374",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:372",
       "field": "system.load.15",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:load AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU cores - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.cores",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU usage - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.user.pct",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU usage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.iowait.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.system.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.user.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Load - $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "System load - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.load.5",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System load - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:324",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:322",
       "field": "system.load.1",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:load AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:353",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:351",
       "field": "system.load.5",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:load AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:374",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:372",
       "field": "system.load.15",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:load AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU cores - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.cores",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU usage - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.user.pct",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU usage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.iowait.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.system.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.user.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Load - $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "System load - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.load.5",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System load - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:324",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:322",
       "field": "system.load.1",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:load AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:353",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:351",
       "field": "system.load.5",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:load AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:374",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:372",
       "field": "system.load.15",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:load AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU cores - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.cores",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU usage - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 17 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.user.pct",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU usage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.iowait.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.system.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.user.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Memory & Process - $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "hostname" },
  {
   "title": "Memory usage - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "memory.used.pct",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND metricset.name:memory AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory usage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.used.bytes",
       "id": "3",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:memory AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "free",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.free",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:memory AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processes by CPU - $hostname",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 25 },
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.process.name",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "1",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "system.process.cpu.total.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:process AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processes by Memory - $hostname",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.process.name",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "system.process.memory.rss.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:process AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Memory & Process - $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Memory usage - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 33 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "memory.used.pct",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND metricset.name:memory AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory usage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.used.bytes",
       "id": "3",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:memory AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "free",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.free",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:memory AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processes by CPU - $hostname",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 33 },
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.process.name",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "1",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "system.process.cpu.total.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:process AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processes by Memory - $hostname",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.process.name",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "system.process.memory.rss.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:process AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Memory & Process - $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Memory usage - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 41 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "memory.used.pct",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND metricset.name:memory AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory usage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.used.bytes",
       "id": "3",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:memory AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "free",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.free",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:memory AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processes by CPU - $hostname",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 41 },
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.process.name",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "1",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "system.process.cpu.total.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:process AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processes by Memory - $hostname",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 41 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.process.name",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "system.process.memory.rss.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:process AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Disk & Network  - $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }, "repeat": "hostname" },
  {
   "title": "Disk Usage - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 49 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "filesystem.used.pct",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND metricset.name:filesystem AND NOT (system.filesystem.mount_point:\"/vagrant\" OR system.filesystem.mount_point:\"/home/vagrant/exchange\" OR system.filesystem.mount_point:\"/vagrant/download\" OR system.filesystem.mount_point:\"/home/vagrant/ansible\") AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Usage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.filesystem.mount_point",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:filesystem AND NOT (system.filesystem.mount_point:\"/vagrant\" OR system.filesystem.mount_point:\"/home/vagrant/exchange\" OR system.filesystem.mount_point:\"/vagrant/download\" OR system.filesystem.mount_point:\"/home/vagrant/ansible\") AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network In/Out (bytes) - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "in.bytes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "in.errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.errors",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "out.bytes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.bytes",
       "hide": true,
       "id": "1",
       "inlineScript": "_value * -1",
       "meta": {},
       "settings": { "script": { "inline": "_value * -1" } },
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "out.errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.errors",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network In/Out (packets) - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "in.packets",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.packets",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "in.dropped",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.dropped",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "out.packets",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.packets",
       "hide": true,
       "id": "1",
       "inlineScript": "_value * -1",
       "meta": {},
       "settings": { "script": { "inline": "_value * -1" } },
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "out.dropped",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.dropped",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Disk & Network  - $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Disk Usage - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 57 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "filesystem.used.pct",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND metricset.name:filesystem AND NOT (system.filesystem.mount_point:\"/vagrant\" OR system.filesystem.mount_point:\"/home/vagrant/exchange\" OR system.filesystem.mount_point:\"/vagrant/download\" OR system.filesystem.mount_point:\"/home/vagrant/ansible\") AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Usage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 57 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.filesystem.mount_point",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:filesystem AND NOT (system.filesystem.mount_point:\"/vagrant\" OR system.filesystem.mount_point:\"/home/vagrant/exchange\" OR system.filesystem.mount_point:\"/vagrant/download\" OR system.filesystem.mount_point:\"/home/vagrant/ansible\") AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network In/Out (bytes) - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "in.bytes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "in.errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.errors",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "out.bytes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.bytes",
       "hide": true,
       "id": "1",
       "inlineScript": "_value * -1",
       "meta": {},
       "settings": { "script": { "inline": "_value * -1" } },
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "out.errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.errors",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network In/Out (packets) - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "in.packets",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.packets",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "in.dropped",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.dropped",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "out.packets",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.packets",
       "hide": true,
       "id": "1",
       "inlineScript": "_value * -1",
       "meta": {},
       "settings": { "script": { "inline": "_value * -1" } },
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "out.dropped",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.dropped",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Disk & Network  - $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Disk Usage - $hostname",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 65 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "filesystem.used.pct",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND metricset.name:filesystem AND NOT (system.filesystem.mount_point:\"/vagrant\" OR system.filesystem.mount_point:\"/home/vagrant/exchange\" OR system.filesystem.mount_point:\"/vagrant/download\" OR system.filesystem.mount_point:\"/home/vagrant/ansible\") AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Usage - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 65 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.filesystem.mount_point",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:filesystem AND NOT (system.filesystem.mount_point:\"/vagrant\" OR system.filesystem.mount_point:\"/home/vagrant/exchange\" OR system.filesystem.mount_point:\"/vagrant/download\" OR system.filesystem.mount_point:\"/home/vagrant/ansible\") AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network In/Out (bytes) - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "in.bytes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "in.errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.errors",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "out.bytes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.bytes",
       "hide": true,
       "id": "1",
       "inlineScript": "_value * -1",
       "meta": {},
       "settings": { "script": { "inline": "_value * -1" } },
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "out.errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.errors",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network In/Out (packets) - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "in.packets",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.packets",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "in.dropped",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.dropped",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "out.packets",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.packets",
       "hide": true,
       "id": "1",
       "inlineScript": "_value * -1",
       "meta": {},
       "settings": { "script": { "inline": "_value * -1" } },
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "out.dropped",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.dropped",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "metricset.module:system AND metricset.name:network AND beat.hostname:$hostname",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}