{
 "title": "System Overview (Graphtie)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "hostname", "label": "Hostname", "query": "servers.*" }
  ]
 },
 "panels": [
  {
   "title": "Load - $hostname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$hostname.loadavg.01_normalized, 3)"
    },
    {
     "target": "aliasByNode(servers.$hostname.loadavg.05_normalized, 3)"
    },
    {
     "target": "aliasByNode(servers.$hostname.loadavg.15_normalized, 3)"
    }
   ]
  },
  {
   "title": "CPU - $hostname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "target": "aliasByNode(servers.$hostname.cpu.total.user, 3, 4)",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "target": "aliasByNode(servers.$hostname.cpu.total.system, 3, 4)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory - $hostname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$hostname.memory.MemFree, 3)"
    },
    {
     "target": "aliasByNode(servers.$hostname.memory.MemTotal, 3)"
    }
   ]
  },
  {
   "title": "Disk - $hostname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$hostname.diskspace.root.byte_free, 4)"
    },
    {
     "target": "aliasByNode(servers.$hostname.diskspace.root.byte_used, 4)"
    }
   ]
  },
  {
   "title": "Network - $hostname",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$hostname.network.*.rx_byte, 3, 4)"
    },
    {
     "target": "aliasByNode(servers.$hostname.network.*.tx_byte, 3, 4)"
    }
   ]
  }
 ]
}